### ISSUE TITLE
No limit to how many text fields users can add to a meme

### ISSUE THREAD

**Issue by AdamGencel** [WeAreNewt/Memixer#44]
as of right now users could potentially add text field indefinitely, and with each text field added the background image scaling is disrupted
![Jul-12-2022 15-07-05](https://user-images.githubusercontent.com/42351914/178497298-49883bbb-4180-4996-a123-cc17ad3b37de.gif)

**Comment by 0xjim** [comment]
Let's add a maximum of 10 text fields @JoaquinBattilana
